name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions: 
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
      # checkout code
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v5

      # set up Node.js
      - name: ðŸ“¦ Setup Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v6
        with: 
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      # Install test framework
      - name: ðŸ”¨ Install Playwright framework
        run: npm ci

      # get allure history
      - name: ðŸ“š Download Allure report history
        uses: actions/checkout@v5
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Install test framework
      - name: ðŸ”¨ Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright Tests
      - name: ðŸ§ª Run Mocha tests
        id: tests
        run: npm run test tests/Todo/*.spec.ts --testenv=evt1
        continue-on-error: true

      # Generate Allure Report
      - name: ðŸ“Š Build Allure Report
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: true

      # Get Test results
      - name: ðŸ“Š Parse test results
        if: always()
        id: test-results
        run: |
          if [ -f test-results/.last-run.json ]; then
            STATUS=$(grep -oP '(?<=status": " )[^",]*' test-results/.last-run.json || echo "unknown")
            FAILED=$(grep -oP '(?<=failedTests": [ )[^]]*' test_report/emailSummary.txt || echo "unknown")
          
            echo "status=$STATUS" >> $GITHUB_OUTPUT
            echo "failedTests=$FAILED" >> $GITHUB_OUTPUT
          else
            echo "status=unknown" >> $GITHUB_OUTPUT
            echo "failedTests=unknown" >> $GITHUB_OUTPUT
          fi
          
      # Archive test reports
      - name: ðŸ“¦ Archive test reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: test-reports
          path: |
            allure_results/
            test-results/
            playwright-report/
            retention-days: 90

      # Publish test reports
      - name: ðŸš€ Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history, playwright-report

      # Add report to summary
      - name: ðŸ“ Add report link to summary
        if: always()
        run: |
          echo "## ðŸ§ª Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ“Š Test Statistics" >> $GITHUB_STEP_SUMMARY
            echo "- **Status:** ${{ steps.test-results.outputs.status }}" >> $GITHUB_STEP_SUMMARY
            echo "- **âŒ FailedTests:** ${{ steps.test-results.outputs.failedTests }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### ðŸ“„ Reports" >> $GITHUB_STEP_SUMMARY
            echo "ðŸ”— [View Allure report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/summary-report.html)" >> $GITHUB_STEP_SUMMARY
            echo "ðŸ”— [view Playwright report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/test-report.html)" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          
            if [ "${{ steps.tests.outcome }}" == "success" ]; then
              echo "### âœ… Status: All tests passed!" >> $GITHUB_STEP_SUMMARY
            else
              echo "### âŒ Status: Some tests failed" >> $GITHUB_STEP_SUMMARY
            fi