name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions: 
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
      # checkout code
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v5

      # set up Node.js
      - name: ðŸ“¦ Setup Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v6
        with: 
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      # Install test framework
      - name: ðŸ”¨ Install Playwright framework
        run: npm ci

      # get allure history
      - name: ðŸ“š Download Allure report history
        uses: actions/checkout@v5
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Install test framework
      - name: ðŸ”¨ Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright Tests
      - name: ðŸ§ª Run Mocha tests
        id: tests
        run: npm run test tests/Todo/*.spec.ts --testenv=evt1
        continue-on-error: true

      # Generate Allure Report
      - name: ðŸ“Š Build Allure Report
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          keep_reports: true

      # Archive test reports
      - name: ðŸ“¦ Archive test reports
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: test-reports
          path: |
            allure_results/
            test-results/
            retention-days: 90

      # Publish test reports
      - name: ðŸš€ Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
